Repository DaniilGumin/WeatherOutlookBot, pull requests merged in 2022-10, with the labels that each got.

#2 Last city
  README.md
  Services/__init__.py
  Services/keyboard.py
  Services/weather.py
  main.py
Labels: documentation, enhancement

#3 refactor: update texts
  Services/weather.py
  main.py
Labels: refactor

#4 In-code Documentation
  Services/weather.py
Labels: documentation
